cmake_minimum_required(VERSION 3.15)

find_package(miniz REQUIRED CONFIG)
set(MINIZ_LIBRARIES miniz::miniz)
if(NOT BUILD_SHARED_LIBS)
    find_package(tinyexr REQUIRED CONFIG)
    find_package(libsquish REQUIRED CONFIG)
    set(TINYEXR_LIBRARIES tinyexr::tinyexr)
    set(LIBSQUISH_LIBRARIES libsquish::libsquish)
    find_package(lodepng REQUIRED CONFIG)
    set(LOADPNG_LIBRARIES lodepng::lodepng)
endif()
if(UNIX AND NOT APPLE)
    find_package(wayland REQUIRED CONFIG)
endif()
