from conan import ConanFile
from conan.tools.build import check_max_cppstd, check_min_cppstd
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import *

required_conan_version = ">=2.1"


class SouffleConan(ConanFile):
    name = "souffle"
    description = "Soufflé is a variant of Datalog for tool designers crafting static analyses, compiled to parallel C++"
    license = "UPL-1.0"
    homepage = "https://github.com/souffle-lang/souffle"
    topics = ("datalog", "logic-programming", "static-analysis", "compiler")
    package_type = None  # application + header library
    settings = "os", "arch", "compiler", "build_type"
    options = {
        "domain_64bit": [True, False],
        "with_curses": [True, False],
        "with_libffi": [True, False],
        "with_openmp": [True, False],
        "with_sqlite": [True, False],
        "with_zlib": [True, False],
    }
    default_options = {
        "domain_64bit": False,
        "with_curses": False,
        "with_libffi": False,
        "with_openmp": True,
        "with_sqlite": False,
        "with_zlib": True,
    }
    options_description = {
        "domain_64bit": "Use 64-bit number values in Datalog tuples (RAM_DOMAIN_SIZE=64)",
        "with_curses": "Enable the ncurses-based provenance display",
        "with_libffi": "Enable libffi (user-defined functors loaded from shared libraries)",
        "with_openmp": "Enable OpenMP parallelism",
        "with_sqlite": "Enable SQLite IO",
        "with_zlib": "Enable libz file compression",
    }

    def export_sources(self):
        export_conandata_patches(self)

    def package_id(self):
        del self.info.settings.compiler

    def layout(self):
        cmake_layout(self, src_folder="src")

    def requirements(self):
        # Propagated to consumers: code generated by souffle includes the runtime
        # headers (include/souffle) and links these libraries when compiled.
        if self.options.with_curses:
            self.requires("ncurses/[^6.4]", transitive_headers=True, transitive_libs=True)
        if self.options.with_zlib:
            self.requires("zlib-ng/[^2.0]", transitive_headers=True, transitive_libs=True)
        if self.options.with_sqlite:
            self.requires("sqlite3/[>=3.44 <4]", transitive_headers=True, transitive_libs=True)
        if self.options.with_openmp:
            self.requires("openmp/system", transitive_headers=True, transitive_libs=True)
        if self.options.with_libffi:
            # Used only by the souffle interpreter binary
            self.requires("libffi/[^3.4]", visible=False)

    def validate(self):
        check_min_cppstd(self, 17)
        check_max_cppstd(self, 17)

    def build_requirements(self):
        if self.settings.os == "Windows":
            self.tool_requires("winflexbison/[^2.5.25]")
        else:
            self.tool_requires("flex/[^2.6.4]")
            self.tool_requires("bison/[^3.8.2]")

    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        rm(self, "Find*.cmake", "cmake")
        apply_conandata_patches(self)

    def generate(self):
        tc = CMakeToolchain(self)
        tc.cache_variables["SOUFFLE_GIT"] = False
        tc.cache_variables["PACKAGE_VERSION"] = self.version
        tc.cache_variables["SOUFFLE_ENABLE_TESTING"] = False
        tc.cache_variables["SOUFFLE_USE_LIBCPP"] = False
        tc.cache_variables["SOUFFLE_DOMAIN_64BIT"] = self.options.domain_64bit
        tc.cache_variables["SOUFFLE_USE_CURSES"] = self.options.with_curses
        tc.cache_variables["SOUFFLE_USE_ZLIB"] = self.options.with_zlib
        tc.cache_variables["SOUFFLE_USE_SQLITE"] = self.options.with_sqlite
        tc.cache_variables["SOUFFLE_USE_OPENMP"] = self.options.with_openmp
        tc.cache_variables["SOUFFLE_USE_LIBFFI"] = self.options.with_libffi
        # Force C++17, don't override. Does not need to be respected for an application-only build.
        tc.blocks.remove("cppstd")
        tc.generate()

        deps = CMakeDeps(self)
        deps.set_property("libffi", "cmake_target_name", "libffi")
        deps.set_property("ncurses", "cmake_target_name", "Curses::NCurses")
        deps.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = []

        # Definitions consumed when compiling souffle-generated C++, mirroring the
        # upstream "compiled" target in src/CMakeLists.txt.
        if self.options.domain_64bit:
            self.cpp_info.defines.append("RAM_DOMAIN_SIZE=64")
        if self.options.with_curses:
            self.cpp_info.defines.append("USE_NCURSES")
        if self.options.with_zlib:
            self.cpp_info.defines.append("USE_LIBZ")
        if self.options.with_sqlite:
            self.cpp_info.defines.append("USE_SQLITE")

        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs = ["pthread"]
